name: flutter_math_katex
description: High-fidelity KaTeX-style Flutter math widget package.
version: 0.1.0
homepage: https://github.com/mehedi8603651/flutter-math-packages
repository: https://github.com/mehedi8603651/flutter-math-packages
issue_tracker: https://github.com/mehedi8603651/flutter-math-packages/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.38.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  provider: ^6.1.5+1
  tuple: ^2.0.2
  flutter_math_model: ^0.1.0
  flutter_math_tex: ^0.1.0
  flutter_math_render_katex: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
