name: flutter_math_model
description: Shared AST and semantic model layer for Flutter math packages.
version: 0.1.0
homepage: https://github.com/mehedi8603651/flutter-math-packages
repository: https://github.com/mehedi8603651/flutter-math-packages
issue_tracker: https://github.com/mehedi8603651/flutter-math-packages/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
