// The MIT License (MIT)
//
// Copyright (c) 2013-2019 Khan Academy and other contributors
// Copyright (c) 2020 znjameswu <znjameswu@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import 'package:flutter_math_model/ast.dart' show MathColor;

// All supported CSS color names
// The following values are obtained from https://developer.mozilla.org/en-US/docs/Web/CSS/color_value
const colorByName = {
  'black': MathColor(0xff000000),
  'silver': MathColor(0xffc0c0c0),
  'gray': MathColor(0xff808080),
  'white': MathColor(0xffffffff),
  'maroon': MathColor(0xff800000),
  'red': MathColor(0xffff0000),
  'purple': MathColor(0xff800080),
  'fuchsia': MathColor(0xffff00ff),
  'green': MathColor(0xff008000),
  'lime': MathColor(0xff00ff00),
  'olive': MathColor(0xff808000),
  'yellow': MathColor(0xffffff00),
  'navy': MathColor(0xff000080),
  'blue': MathColor(0xff0000ff),
  'teal': MathColor(0xff008080),
  'aqua': MathColor(0xff00ffff),
  'orange': MathColor(0xffffa500),
  'aliceblue': MathColor(0xfff0f8ff),
  'antiquewhite': MathColor(0xfffaebd7),
  'aquamarine': MathColor(0xff7fffd4),
  'azure': MathColor(0xfff0ffff),
  'beige': MathColor(0xfff5f5dc),
  'bisque': MathColor(0xffffe4c4),
  'blanchedalmond': MathColor(0xffffebcd),
  'blueviolet': MathColor(0xff8a2be2),
  'brown': MathColor(0xffa52a2a),
  'burlywood': MathColor(0xffdeb887),
  'cadetblue': MathColor(0xff5f9ea0),
  'chartreuse': MathColor(0xff7fff00),
  'chocolate': MathColor(0xffd2691e),
  'coral': MathColor(0xffff7f50),
  'cornflowerblue': MathColor(0xff6495ed),
  'cornsilk': MathColor(0xfffff8dc),
  'crimson': MathColor(0xffdc143c),
  'cyan': MathColor(0xff00ffff),
  'darkblue': MathColor(0xff00008b),
  'darkcyan': MathColor(0xff008b8b),
  'darkgoldenrod': MathColor(0xffb8860b),
  'darkgray': MathColor(0xffa9a9a9),
  'darkgreen': MathColor(0xff006400),
  'darkgrey': MathColor(0xffa9a9a9),
  'darkkhaki': MathColor(0xffbdb76b),
  'darkmagenta': MathColor(0xff8b008b),
  'darkolivegreen': MathColor(0xff556b2f),
  'darkorange': MathColor(0xffff8c00),
  'darkorchid': MathColor(0xff9932cc),
  'darkred': MathColor(0xff8b0000),
  'darksalmon': MathColor(0xffe9967a),
  'darkseagreen': MathColor(0xff8fbc8f),
  'darkslateblue': MathColor(0xff483d8b),
  'darkslategray': MathColor(0xff2f4f4f),
  'darkslategrey': MathColor(0xff2f4f4f),
  'darkturquoise': MathColor(0xff00ced1),
  'darkviolet': MathColor(0xff9400d3),
  'deeppink': MathColor(0xffff1493),
  'deepskyblue': MathColor(0xff00bfff),
  'dimgray': MathColor(0xff696969),
  'dimgrey': MathColor(0xff696969),
  'dodgerblue': MathColor(0xff1e90ff),
  'firebrick': MathColor(0xffb22222),
  'floralwhite': MathColor(0xfffffaf0),
  'forestgreen': MathColor(0xff228b22),
  'gainsboro': MathColor(0xffdcdcdc),
  'ghostwhite': MathColor(0xfff8f8ff),
  'gold': MathColor(0xffffd700),
  'goldenrod': MathColor(0xffdaa520),
  'greenyellow': MathColor(0xffadff2f),
  'grey': MathColor(0xff808080),
  'honeydew': MathColor(0xfff0fff0),
  'hotpink': MathColor(0xffff69b4),
  'indianred': MathColor(0xffcd5c5c),
  'indigo': MathColor(0xff4b0082),
  'ivory': MathColor(0xfffffff0),
  'khaki': MathColor(0xfff0e68c),
  'lavender': MathColor(0xffe6e6fa),
  'lavenderblush': MathColor(0xfffff0f5),
  'lawngreen': MathColor(0xff7cfc00),
  'lemonchiffon': MathColor(0xfffffacd),
  'lightblue': MathColor(0xffadd8e6),
  'lightcoral': MathColor(0xfff08080),
  'lightcyan': MathColor(0xffe0ffff),
  'lightgoldenrodyellow': MathColor(0xfffafad2),
  'lightgray': MathColor(0xffd3d3d3),
  'lightgreen': MathColor(0xff90ee90),
  'lightgrey': MathColor(0xffd3d3d3),
  'lightpink': MathColor(0xffffb6c1),
  'lightsalmon': MathColor(0xffffa07a),
  'lightseagreen': MathColor(0xff20b2aa),
  'lightskyblue': MathColor(0xff87cefa),
  'lightslategray': MathColor(0xff778899),
  'lightslategrey': MathColor(0xff778899),
  'lightsteelblue': MathColor(0xffb0c4de),
  'lightyellow': MathColor(0xffffffe0),
  'limegreen': MathColor(0xff32cd32),
  'linen': MathColor(0xfffaf0e6),
  'magenta (synonym of fuchsia)': MathColor(0xffff00ff),
  'mediumaquamarine': MathColor(0xff66cdaa),
  'mediumblue': MathColor(0xff0000cd),
  'mediumorchid': MathColor(0xffba55d3),
  'mediumpurple': MathColor(0xff9370db),
  'mediumseagreen': MathColor(0xff3cb371),
  'mediumslateblue': MathColor(0xff7b68ee),
  'mediumspringgreen': MathColor(0xff00fa9a),
  'mediumturquoise': MathColor(0xff48d1cc),
  'mediumvioletred': MathColor(0xffc71585),
  'midnightblue': MathColor(0xff191970),
  'mintcream': MathColor(0xfff5fffa),
  'mistyrose': MathColor(0xffffe4e1),
  'moccasin': MathColor(0xffffe4b5),
  'navajowhite': MathColor(0xffffdead),
  'oldlace': MathColor(0xfffdf5e6),
  'olivedrab': MathColor(0xff6b8e23),
  'orangered': MathColor(0xffff4500),
  'orchid': MathColor(0xffda70d6),
  'palegoldenrod': MathColor(0xffeee8aa),
  'palegreen': MathColor(0xff98fb98),
  'paleturquoise': MathColor(0xffafeeee),
  'palevioletred': MathColor(0xffdb7093),
  'papayawhip': MathColor(0xffffefd5),
  'peachpuff': MathColor(0xffffdab9),
  'peru': MathColor(0xffcd853f),
  'pink': MathColor(0xffffc0cb),
  'plum': MathColor(0xffdda0dd),
  'powderblue': MathColor(0xffb0e0e6),
  'rosybrown': MathColor(0xffbc8f8f),
  'royalblue': MathColor(0xff4169e1),
  'saddlebrown': MathColor(0xff8b4513),
  'salmon': MathColor(0xfffa8072),
  'sandybrown': MathColor(0xfff4a460),
  'seagreen': MathColor(0xff2e8b57),
  'seashell': MathColor(0xfffff5ee),
  'sienna': MathColor(0xffa0522d),
  'skyblue': MathColor(0xff87ceeb),
  'slateblue': MathColor(0xff6a5acd),
  'slategray': MathColor(0xff708090),
  'slategrey': MathColor(0xff708090),
  'snow': MathColor(0xfffffafa),
  'springgreen': MathColor(0xff00ff7f),
  'steelblue': MathColor(0xff4682b4),
  'tan': MathColor(0xffd2b48c),
  'thistle': MathColor(0xffd8bfd8),
  'tomato': MathColor(0xffff6347),
  'turquoise': MathColor(0xff40e0d0),
  'violet': MathColor(0xffee82ee),
  'wheat': MathColor(0xfff5deb3),
  'whitesmoke': MathColor(0xfff5f5f5),
  'yellowgreen': MathColor(0xff9acd32),
  'rebeccapurple': MathColor(0xff663399),
  'transparent': MathColor(0x00000000),
};
